# yaml for acr build and push 

trigger:
  none

pool:
  name: dockerpool
  demands:
  - agent.name -equals   dockeragent

stages:
  - stage: docker_build
    jobs:
      - job: "docker_build"
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Dockerhub-to-pipeline'
            repository: 'pawan071202/class-repository'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'